Models/CarListViewModel.cs
using AspNetCore_ShopCars.Data.Models;
using System.Collections.Generic;

namespace AspNetCore_ShopCars.Models
{
    public class CarListViewModel
    {
        public IEnumerable<Car> AllCars { get; set; }

        public Car Car { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace AspNetCore_ShopCars.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/User.cs
using System;

namespace AspNetCore_ShopCars.Models
{
    public class User
    {
        public Guid ID { get; set; }

        public string Name { get; set; }

        public string Login { get; set; }

        public string Password { get; set; }
    }
}

ViewModels/UserLoginModel.cs
using System.ComponentModel.DataAnnotations;

namespace AspNetCore_ShopCars.ViewModels
{
    public class UserLoginModel
    {
        [Required(ErrorMessage = "Не указан логин")]
        public string Login { get; set; }

        [Required(ErrorMessage = "Не указан пароль")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

ViewModels/UserRegistrationModel.cs
using System.ComponentModel.DataAnnotations;

namespace AspNetCore_ShopCars.ViewModels
{
    public class UserRegistrationModel
    {
        [Required(ErrorMessage = "Не указано имя")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Не указан логин")]
        public string Login { get; set; }

        [Required(ErrorMessage = "Не указан пароль")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Пароль введен неверно")]
        public string ConfirmPassword { get; set; }
    }
}

Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using AspNetCore_ShopCars.Models;
using AspNetCore_ShopCars.Data;
using AspNetCore_ShopCars.ViewModels;
using System;

namespace AspNetCore_ShopCars.Controllers
{
    public class AuthController : Controller
    {
        private AppDBContent db;

        public AuthController(AppDBContent context)
        {
            db = context;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(UserLoginModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await db.Users.FirstOrDefaultAsync(u => u.Login == model.Login && u.Password == model.Password);
                if (user != null)
                {
                    await Authenticate(model.Login); // аутентификация

                    return RedirectToAction("Index", "Home");
                }

                ModelState.AddModelError("", "Некорректные логин и(или) пароль");
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Registration()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Registration(UserRegistrationModel model)
        {
            if (ValidateRegistration(model) && ModelState.IsValid)
            {
                User user = await db.Users.FirstOrDefaultAsync(u => u.Login == model.Login);
                if (user == null)
                {
                    // добавляем пользователя в бд
                    db.Users.Add(new User { ID = Guid.NewGuid(), Name = model.Name, Login = model.Login, Password = model.Password });
                    await db.SaveChangesAsync();

                    await Authenticate(model.Login); // аутентификация

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "Пользователь с таким логином уже существует");
                }
            }

            return View(model);
        }

        private async Task Authenticate(string userName)
        {
            // создаем один claim
            var claims = new List<Claim>
            {
                new Claim(ClaimsIdentity.DefaultNameClaimType, userName)
            };

            // создаем объект ClaimsIdentity
            ClaimsIdentity id = new ClaimsIdentity(claims, "ApplicationCookie", ClaimsIdentity.DefaultNameClaimType, ClaimsIdentity.DefaultRoleClaimType);
            
            // установка аутентификационных куки
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(id));
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login", "Auth");
        }

        /// <summary>
        /// Валидация полей при регистрации.
        /// </summary>
        private bool ValidateRegistration(UserRegistrationModel model)
        {
            bool validate = true;

            if (model.Name == null)
            {
                ModelState.AddModelError("", "Укажите имя");
                validate = false;
            }

            if (model.Login == null)
            {
                ModelState.AddModelError("", "Укажите логин");
                validate = false;
            }

            if (model.Password == null)
            {
                ModelState.AddModelError("", "Укажите пароль");
                validate = false;
            }

            if (model.Password != null && model.ConfirmPassword == null)
            {
                ModelState.AddModelError("", "Повторите ввод пароля");
                validate = false;
            }

            if (model.Password != null && model.ConfirmPassword != null
                && model.Password != model.ConfirmPassword)
            {
                ModelState.AddModelError("", "Пароли должны совпадать");
                validate = false;
            }

            return validate;
        }
    }
}

Controllers/CarCardController.cs
using AspNetCore_ShopCars.Data.Interfaces;
using AspNetCore_ShopCars.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;

namespace AspNetCore_ShopCars.Controllers
{
    public class CarCardController : Controller
    {
        private readonly ICars _cars;

        public CarCardController(ICars cars)
        {
            _cars = cars;
        }

        [Authorize]
        public IActionResult CarCardView(Guid id)
        {
            CarListViewModel obj = new CarListViewModel();
            obj.Car = _cars.GetCarByID(id);
            ViewBag.Title = obj.Car.Name;
            return View(obj);
        }
    }
}

Controllers/HomeController.cs
using AspNetCore_ShopCars.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace AspNetCore_ShopCars.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ShopController.cs
using AspNetCore_ShopCars.Data.Interfaces;
using AspNetCore_ShopCars.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCore_ShopCars.Controllers
{
    public class ShopController : Controller
    {
        private readonly ICars _cars;
        
        public ShopController(ICars cars)
        {
            _cars = cars;
        }

        [Authorize]
        public ViewResult ListCarsView()
        {
            ViewBag.Title = "Магазин";
            CarListViewModel obj = new CarListViewModel();
            obj.AllCars = _cars.GetAllCars;
            return View(obj);
        }
    }
}

Views/CarCard/CarCardView.cshtml
@{
    var car = Model.Car;
    <div class="row">
        <img class="img-thumbnail" src="@car.ImageUrl" alt="@car.Name" />
    </div>
    <div class="row">
        <div class="col">
            <div class="row">
                <h1>Модель: @car.Name</h1>
            </div>
            <div class="row">
                <h1>Описание</h1>
            </div>
            <div class="row">
                <p>@car.Description</p>
            </div>
        </div>
        <div class="col">
            <div class="row">
                <h1>Стоимость: @car.Price</h1>
            </div>
        </div>
    </div>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Добро пожаловать!</h1>
    <p>Это домашняя страница магазина автомобилей.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Магазин автомобилей</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Автомобили</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Shop" asp-action="ListCarsView">Магазин</a>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <p class="m-auto">@User.Identity.Name</p>
                        @{
                            if (User.Identity.Name != null)
                            {
                                <a class="nav-link text-dark" asp-controller="Auth" asp-action="Logout">Выход</a>
                            }
                            else
                            {
                                <a class="nav-link text-dark" asp-controller="Auth" asp-action="Login">Войти</a>
                            }
                        }
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Garaev Rustam - <a asp-area="" asp-controller="Home" asp-action="Privacy">На главную</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shop/ListCarsView.cshtml
<div class="pt-2">
    <h1>Все автомобили</h1>
    <div class="row">
        @{
            foreach (var car in Model.AllCars)
            {
                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm p-1">
                        <img class="img-thumbnail" src="@car.ImageUrl" alt="@car.Name" />
                        <div class="card-body">
                            <h2>Модель: @car.Name</h2>
                            <p>Цена: @car.Price?.ToString("c")</p>
                            <p><a class="btn btn-warning" asp-controller="CarCard" asp-action="CarCardView" asp-route-id="@car.ID">Подробнее</a></p>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
</div>